import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import axios from 'axios';
import { Character, GetCharacterResults } from '../types';
import imageLoader from '../imageLoader';

const Home: NextPage<{ characters: Character[] }> = ({ characters }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {characters.map(character => {
        return (
          <div key={character.id}>
            {character.name}
            <Image
              loader={imageLoader}
              unoptimized
              src={character.image}
              alt={character.name}
              width="200"
              height="200"
            />
          </div>
        );
      })}
    </div>
  );
};

export const getStaticProps: GetStaticProps = async context => {
  const res = await axios.get('https://rickandmortyapi.com/api/character');
  const data: GetCharacterResults = await res.data.results;
  return {
    props: {
      characters: data,
    },
  };
};

export default Home;
