import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import axios from 'axios';

const Home: NextPage = ({ characters }: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {JSON.stringify(characters)}
    </div>
  );
};

export const getStaticProps: GetStaticProps = async context => {
  const res = await axios.get('https://rickandmortyapi.com/api/character');

  return {
    props: {
      characters: res.data,
    },
  };
};

export default Home;
