import type { NextPage } from 'next';
import Head from 'next/head';
import { SiProbot } from 'react-icons/si';
import { useRef } from 'react';

const Home: NextPage = () => {
  const inputRef = useRef<HTMLTextAreaElement>(null);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (inputRef.current) {
      // 타입가드
      console.log(inputRef.current.value);
    }
  };

  return (
    <>
      <Head>
        <title>OpenAPI Plugin Usecase</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>변수명 생성기</h1>
        <SiProbot />
      </header>
      <main>
        <h3></h3>
        <form onSubmit={handleSubmit}>
          <label htmlFor="description">설명</label>
          <textarea
            ref={inputRef}
            name="description"
            id="description"
            placeholder="생성할 변수나 함수의 역할을 설명해주세요"
          />
          <button type="submit">제출</button>
        </form>
      </main>
    </>
  );
};

export default Home;
