import type { NextPage } from 'next';
import Head from 'next/head';
import { SiProbot } from 'react-icons/si';
import { useRef, useState } from 'react';

const Home: NextPage = () => {
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const [result, setResult] = useState('');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!inputRef.current) return; // 타입가드
    const descriptionValue = inputRef.current.value;

    try {
      const response = await fetch('/api/generate', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ descriptionValue }),
      });

      const data = await response.json();
      if (response.status !== 200) {
        throw (
          data.error || new Error(`요청 실패! 상태코드: ${response.status}`)
        );
      }
      setResult(data.result);
    } catch (error) {
      alert(error);
    }

    inputRef.current.value = '';
  };

  return (
    <>
      <Head>
        <title>자바스크립트 헬퍼</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>자바스크립트 질문 받습니다</h1>
        <SiProbot />
      </header>
      <main>
        <h3></h3>
        <form onSubmit={handleSubmit}>
          <label htmlFor="description">설명</label>
          <textarea
            ref={inputRef}
            name="description"
            id="description"
            placeholder="질문내용을 입력하세요"
          />
          <button type="submit">제출</button>
        </form>
        <div>
          <span>결과</span>
          <pre>{result}</pre>
        </div>
      </main>
    </>
  );
};

export default Home;
